# Configuration fragment for mutual anchoring.

wrist-rest:
  include: true
  style: threaded
  mounts:
  - fasteners:
      diameter: 6
      length: 55
      height:
        first: 4
        increment: 16
    anchoring: mutual
    blocks:
      width: 15
      case-side:
        position:
          anchor: t4
          offset: [2, 4]
        depth: 9
      plinth-side:
        position:
          anchor: plinth-left
          offset: [10, 4]
        depth: 9.8
        pocket-height: -100
      aliases:
        wr0c: case-side
        wr0p: plinth-side
