# Configuration fragment for a simple back plate.
# This is not in an immediately useable state as of v0.4.0.
# For the back plate to be meaningful, it would be necessary to replace the
# rear housing with ordinary walls and find another site for the MCU etc.

case:
  rear-housing:
    include: false
  back-plate:
    include: true
