# Configuration fragment for the base of a 62-key DMOTE.

keys:
  styles:
    maquette-dsa:  # Repeated from opt/base.yaml.
      style: maquette
      skirt-length: 4.6
      top-size: [12.7, 12.7, 3.3]
    minimal-short:  # A printable minimal key with a thin top.
      style: minimal
      top-size: [9, 9, 1.6]
      skirt-thickness: 2.4
    minimal-tall:  # Similar but with a thicker plate above the stem.
      style: minimal
      top-size: [9, 9, 3]
      skirt-thickness: 2.4
key-clusters:
  main:
    position:
      anchor: origin
      offset: [0, 0, 17]
    matrix-columns:
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 3
    - rows-above-home: 1
      rows-below-home: 2
    - rows-below-home: 2
    - rows-below-home: 2
    aliases:
      m00: [0, first]
      m01: [1, first]
      m02: [2, first]
      m03: [3, first]
      back0: [0, last]
      back1: [1, last]
      m10: [3, last]
      m11: [3, 0]
      m12: [4, last]
      m13: [last, last]
      near-right: [last, first]
  thumb0:
    position:
      anchor: m01
      offset: [-6, -14, 27]
    matrix-columns:
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
    aliases:
      tc: [first, 0]
      t1: [first, last]
      t2: [last, last]
      t3: [last, first]
      t4: [first, first]
  thumb1:
    position:
      anchor: t4
      offset: [-12, 5, -17.5]
    matrix-columns:
    - rows-above-home: 1
    aliases:
      t0: [first, last]
      t5: [first, first]
  aux0:
    position:
      anchor: m12
      offset: [1.5, 15, 5]
    matrix-columns:
    - rows-above-home: 0
    - rows-above-home: 0
    aliases:
      a0: [0, 0]
      a1: [1, 0]
by-key:
  clusters:
    main:
      parameters:
        layout:
          matrix:
            neutral:
              column: 2
            separation:
              row: -0.5
              column: 0
          pitch:
            base: 0.5
            progressive: 0.3
            intrinsic: -0.1
          roll:
            base: 0.2
            progressive: 0.06
          yaw:
            base: 0.03
      columns:
        "0":
          parameters:
            key-style: minimal-tall
            layout:
              matrix:
                separation:
                  row: -1.2
              pitch:
                base: 0.34
                progressive: 0.6
                intrinsic: 0
              roll:
                intrinsic: 0.3
              yaw:
                base: -0.04
              translation:
                mid: [0.5, -10, 4]
            wall:
              north:
                extent: 0
              south:
                extent: 0
          rows:
            "0":
              parameters:
                key-style: minimal-short
                layout:
                  translation:
                    early: [0, 0, -1]
        "1":
          parameters:
            key-style: maquette-dsa
            layout:
              matrix:
                separation:
                  row: -0.9
              pitch:
                base: 0.6
                progressive: 0.4
              translation:
                mid: [0, -1, 0]
            wall:
              north:
                extent: 0
              south:
                extent: 0
              west:
                extent: 0
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.3
                  yaw:
                    intrinsic: -0.03
                  translation:
                    early: [-1, -5.2, 8]
                channel:
                  top-width: 15
            "-1":
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.2
                  translation:
                    early: [0, -0.6, 2]
            "0":
              parameters:
                key-style: minimal-short
                layout:
                  translation:
                    early: [1, 0, 0]
            "1":
              parameters:
                key-style: minimal-tall
                layout:
                  translation:
                    early: [1, -1, 0]
        "2":
          parameters:
            layout:
              pitch:
                progressive: 0.4
              translation:
                mid: [0, 3, -3]
            wall:
              north:
                extent: 0
              east:
                extent: 1
              south:
                extent: 1
              west:
                extent: 0
          rows:
            "-3":
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.7
                  translation:
                    early: [0, -14, 7]
                wall:
                  east:
                    extent: 4
            "-2":
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.3
                  translation:
                    early: [0, -3, 2.5]
            last:
              parameters:
                key-style: minimal-tall
                layout:
                  translation:
                    early: [0, -1, 0]
        "3":
          parameters:
            layout:
              pitch:
                base: 0.4
                progressive: 0.35
              translation:
                mid: [0, -2, 0]
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.3
                  yaw:
                    intrinsic: 0.03
                  translation:
                    early: [0.9, -4, 5]
                wall:
                  south:
                    perpendicular: -12
            last:
              parameters:
                layout:
                  pitch:
                    intrinsic: 0.3
                  translation:
                    early: [0, 4, 1]
                wall:
                  north:
                    extent: 0
                  east:
                    extent: 1
        "4":
          parameters:
            layout:
              matrix:
                separation:
                  row: -0.8
              pitch:
                base: 0.6
                progressive: 0.5
              yaw:
                base: 0.1
              translation:
                late: [0.6, -5, 5.5]
            wall:
              north:
                extent: 1
          rows:
            last:
              parameters:
                layout:
                  pitch:
                    intrinsic: 0.2
                  translation:
                    mid: [0, 3.5, 2]
        "5":
          parameters:
            layout:
              matrix:
                separation:
                  row: -0.8
              pitch:
                base: 0.6
                progressive: 0.5
              yaw:
                base: 0.12
              translation:
                late: [1, -6, 5.5]
            wall:
              north:
                extent: 1
          rows:
            last:
              parameters:
                layout:
                  pitch:
                    intrinsic: 0.2
                  translation:
                    mid: [0, 3.5, 2]
    thumb0:
      parameters:
        layout:
          matrix:
            neutral:
              column: 1
            separation:
              column: 0.1
          roll:
            base: -1.45
            progressive: 0.3
          pitch:
            base: -0.2
            progressive: 0.25
          yaw:
            base: 0.9
        wall:
          north:
            extent: 1
          east:
            extent: 4
          south:
            extent: 0
          west:
            extent: 0
      columns:
        first:
          parameters:
            layout:
              pitch:
                progressive: 0.37
              translation:
                mid: [0, 3, 0]
            wall:
              north:
                extent: 4
                perpendicular: -6
          rows:
            first:
              parameters:
                layout:
                  translation:
                    early: [0, -1.5, -1]
                  pitch:
                    intrinsic: -0.3
                wall:
                  east:
                    extent: 0
                  south:
                    extent: 1
                    parallel: -2
            last:
              parameters:
                layout:
                  translation:
                    early: [0, 0, 5]
        last:
          parameters:
            layout:
              translation:
                mid: [0, -7, 0]
          rows:
            first:
              parameters:
                layout:
                  translation:
                    early: [-0.5, -1.5, -1]
                  pitch:
                    intrinsic: -0.3
                  yaw:
                    intrinsic: 0.05
            last:
              parameters:
                layout:
                  translation:
                    early: [0.5, 1, 0]
                  yaw:
                    intrinsic: -0.1
                wall:
                  north:
                    perpendicular: -11
                  east:
                    perpendicular: -11
    thumb1:
      parameters:
        layout:
          roll:
            base: -1.2
          pitch:
            base: -0.4
            progressive: 0.8
          yaw:
            base: 0.8
        wall:
          north:
            extent: 0
          east:
            extent: 0
          south:
            extent: 0
          west:
            extent: 0
      columns:
        first:
          rows:
            first:
              parameters:
                layout:
                  translation:
                    early: [-0.3, 1, -2]
                  roll:
                    intrinsic: 0
                  yaw:
                    intrinsic: 0 #.1
            last:
              parameters:
                layout:
                  roll:
                    intrinsic: 0
    aux0:
      parameters:
        key-style: minimal-tall
        layout:
          pitch:
            base: 0
        wall:
          north:
            extent: 0
          east:
            extent: 1
          south:
            extent: 1
          west:
            extent: 0
      columns:
        last:
          parameters:
            layout:
              translation:
                early: [-0.5, 0, 0]
secondaries:
- alias: mt0a  # Main-to-thumb0 cluster bridge point 0a.
  anchor: m00
  corner: SSE
  segment: 0
  offset: [0, -2, 2]
- alias: mt0b
  anchor: mt0a
  offset: [4, -3, 16]
- alias: mt0c
  anchor: mt0b
  offset: [6, -2, 1]
- alias: rh-0  # A shim for wall posts being thinner than rear housing posts.
  anchor: rear-housing
  corner: ESE
  segment: 1
  offset: [0.75, -0.75, 0]
- alias: rh-1
  anchor: rh-0
  offset: [0, 0, -20]
case:
  rear-housing:
    include: true
    position:
      offsets:
        north: 15
        east: -0.2
        south: -1.8
        west: 2
    height: 50.95
    fasteners:
      diameter: 6
      bosses: true
      west:
        include: true
        offset: 0
      east:
        include: true
        offset: -13
  back-plate:
    beam-height: 20
    fasteners:
      diameter: 6
      distance: 30
    position:
      anchor: back1
      offset: [0, 0, 0]
  bottom-plate:
    include: true
    thickness: 0.8
    installation:
      thickness: 2.5
      fasteners:
        diameter: 4
        length: 8.5
        positions:
        - anchor: rear-housing
          corner: NNW
          offset: [3, -4]
        - anchor: rear-housing
          corner: NNE
          offset: [-2.5, -11]
        - anchor: a1
          corner: ENE
          offset: [-4.5, -3.5]
        - anchor: near-right
          corner: ESE
          offset: [-5, 3]
        - anchor: t4
          corner: SSW
          offset: [-1, 4]
        - anchor: t1
          corner: NNW
          offset: [3.5, -3]
  leds:
    include: true
    amount: 3
    # Settings here are for WS2818 diodes at 17 mm intervals.
    housing-size: 5.5  # Real size: 5 mm.
    emitter-diameter: 4
    interval: 16.8
  tweaks:
  # First, a bunch of extra webbing at the four corners of the thumb0 cluster:
  - hull-around:
    - [t0, NNW]
    - [t0, NNE]
    - [t1, NNW]
  - hull-around:
    - [t2, NNW, 0, 1]
    - [t2, NNE, 0, 1]
    - [t1, NNE, 0, 1]
  - hull-around:
    - [tc, SSE]
    - [t3, WSW]
    - [t4, ENE]
  # Near upper corner:
  - chunk-size: 3
    hull-around:
    - [t4, ENE]
    - [t4, SSE]
    - [t3, WSW]
    - hull-around:
      - [t3, SSE, 0, 3]
      - [t3, ESE, 0, 3]
  # Webbing at the outer m00–m01 triangle at the edge of the cluster gap:
  - chunk-size: 3
    hull-around:
    - [m00, SSW]
    - [m00, SSE]
    - [mt0a]
    - hull-around:
      - [m00, NNE]
      - [m01, NNW]
    - [m01, SSW]
  # A shield down the whole near wall of the thumb0 cluster:
  - chunk-size: 3
    hull-around:
    - hull-around:
      - [t3, ESE, 0, 1]
      - [t3, SSE, 0, 1]
    - [t3, SSE, 3, 4]
    - hull-around:
      - [t4, ESE, 0, 1]
      - [t4, SSE, 0, 1]
    - [t4, SSE, 3, 4]
    - hull-around:
      - [t4, WSW, 0, 1]
      - [t4, SSW, 0, 1]
    - [t4, SSW, 3, 4]
  # Plating over the cluster gap:
  - chunk-size: 2
    hull-around:
    - [t1, NNE, 0, 4]
    - [t2, NNE, 0, 4]
    - [t2, ENE, 0, 4]
  # Cluster gap, west side:
  - chunk-size: 3
    hull-around:
    - [t1, NNW, 3, 4]
    - [m00, WSW, 2, 3]
    - [t1, NNE, 3, 4]
    - [m00, WSW, 0, 1]
    - [t2, NNE, 3, 4]
  # Cluster gap between m00–m02 and t2, taking a low road under the secondaries:
  - chunk-size: 3
    hull-around:
    - [m00, SSW]
    - hull-around:
      - [t2, NNE, 4]
      - [t2, ENE, 4]
    - [mt0a]
    - [mt0b]
    - [m01, SSW]
    - [mt0c]
    - [m01, SSE]
    - hull-around:
      - [m02, NNW]
      - [m02, SSW]
  # More cluster gap, taking a high road over the secondaries:
  - chunk-size: 3
    hull-around:
    - [t2, ENE, 4]
    - [mt0b]
    - [t2, ESE, 4]
    - [mt0c]
    - [t3, ENE, 4]
    - [m02, SSW]
  # The west side of m02:
  - hull-around:
    - [m01, SSE]
    - [m02, WNW]
    - [m02, WSW]
  # The eastern topside plate, ending in a wedge between m02 and m03:
  - chunk-size: 3
    hull-around:
    - [m02, WSW]
    - [t3, NNE, 4]
    - [m02, SSW]
    - hull-around:
      - [t3, ESE, 3, 4]
      - [t3, SSE, 3, 4]
    - hull-around:
      - [m02, ESE, 3, 4]
      - [m02, SSE, 3, 4]
    - [t4, SSE, 3, 4]
    - [m02, ENE, 3, 4]
    - [t4, SSW, 3, 4]
    - [m03, SSW, 3, 4]
  # The low eastern plate:
  - chunk-size: 3
    hull-around:
    - hull-around:
      - [m02, ESE, 3, 4]
      - [m02, SSE, 3, 4]
    - [m02, ENE, 3, 4]
  # A triangular southern wall of m02:
  - hull-around:
    - [m02, SSW, 0, 1]
    - [m02, SSE, 0, 3]
    - [m02, ESE, 0, 3]
  # Webbing between thumb0 and thumb1:
  - chunk-size: 2
    hull-around:
    - hull-around:
      - [t1, NNW]
      - [t0, NNE]
    - hull-around:
      - [t1, SSW]
      - [t0, SSE]
    - hull-around:
      - [tc, NNW]
      - [t0, SSE]
    - hull-around:
      - [tc, SSW]
      - [t5, NNE]
    - [t4, NNW]
  # Lower near corner:
  - chunk-size: 3
    hull-around:
    - [t5, NNE]
    - [t4, NNW]
    - [t5, SSE]
    - [t4, SSW]
    - [t5, SSW]
  # A plate to ground beneath the thumb clusters:
  - at-ground: true
    chunk-size: 2
    hull-around:
    - [m00, WSW, 2, 3]
    - [t1, NNW, 3, 4]
    - [t1, NNW, 0, 1]
    - [t0, WNW, 0, 1]
    - [t0, WSW, 0, 1]
    - [t5, WNW, 0, 1]
    - [t5, WSW, 0, 1]
    - [t5, SSW, 0, 1]
    - [t4, SSW, 0, 1]
    - [t4, SSW, 3, 4]
    - [m03, SSW, 3, 4]
  # Strengthening the wall between m11 and m12.
  - hull-around:
    - [a0, SSW]
    - [m10, ESE]
    - [m11, ENE]
    - [m11, ESE]
    - [m12, WNW]
    - [m12, WSW]
  # Plating over the main-aux cluster gap.
  - chunk-size: 3
    hull-around:
    - [m10, ENE, 1]
    - [a0, WNW, 0, 1]
    - [a0, WSW, 0, 1]
    - [m10, ESE]
    - [m12, NNW, 0, 1]
  # More plating over the main-aux cluster gap, starting with a bulkhead to
  # strengthen the transition to the rear housing.
  - chunk-size: 3
    hull-around:
    - [rh-0]
    - [rh-1]
    - [m10, ENE, 1]
    - [a0, WNW]
    - [m10, ESE, 0, 1]
    - [a0, WSW]
    - [m12, NNW, 0, 1]
    - [a0, SSE, 0, 1]
    - [m12, NNE, 0, 1]
    - [a1, SSW, 0, 1]
    - [m13, NNW, 0, 1]
    - [a1, SSE, 0, 1]
    - [m13, NNE, 0, 1]
    - [a1, ESE, 0, 1]
    - [m13, ENE, 0, 1]
  # A prettier outer corner:
  - hull-around:
    - [a1, ENE, 0, 1]
    - [m13, ENE, 2, 4]
    - [a1, ESE, 0, 1]
  # A plate to ground at the south-east corner of the rear housing.
  - at-ground: true
    chunk-size: 2
    hull-around:
    - [rear-housing, ESE, 1]
    - [rh-1]  # A shim to align the plate with the housing wall.
    - [a0, WNW, 0, 1]
    - [a0, NNW, 0, 1]
    - [a1, NNE, 0, 1]
    - [a1, ENE, 0, 1]
  - at-ground: true
    chunk-size: 2
    hull-around:
    - [a1, ENE, 0, 1]
    - [m13, ENE, 2, 4]
  # Bottom-only plating at the main-aux cluster gap:
  - at-ground: true
    above-ground: false
    hull-around:
    - [m13, ESE, 3]
    - [m13, ENE, 3]
    - [a1, ESE, 1]
    - [a1, ENE, 1]
    - [a1, NNE, 1]
    - [a0, NNW]
    - [m11, SSW]
  # Bottom-only plating to compensate for the aux cluster breaking up the
  # ground-level profile of the main cluster:
  - at-ground: true
    above-ground: false
    hull-around:
    - [m11, SSW]
    - [a0, NNW]
    - [m10, ENE, 3]
    - [rear-housing, ESE]
    - [rear-housing, WSW]
    - [back0, WNW, 3]
    - [back0, WSW, 3]
mcu:
  type: promicro
  margin: 0.25
  position:
    prefer-rear-housing: true
    anchor: back1
    corner: ENE
    offset: [-1, 0, 2]
  support:
    style: lock
    height-factor: 0.6
    lateral-spacing: 2.5
    lock:
      fastener:
        diameter: 4
      socket:
        thickness: 1.5
      bolt:
        clearance: 2.5
        overshoot: 1
        mount-length: 11
        mount-thickness: 6
    stop:
      anchor: back1
      direction: east
      gripper:
        notch-depth: 0.4
        total-depth: 5
        grip-width: 0.6
connection:
  socket-size: [10, 11, 17.7]  # 616E minus the vertical bar is 10 mm wide.
  position:
    prefer-rear-housing: true
    anchor: back1
    corner: ENE
    raise: true
wrist-rest:
  position:
    offset: [83, -90]
  plinth-height: 2
  shape:
    spline:
      main-points:
      - position: [0, 32]
        alias: plinth-left
      - position: [20, 40]
        alias: plinth-middle
      - position: [35, 38]
      - position: [41, 50]
      - position: [50, 63]
      - position: [68, 62]
        alias: plinth-right
      - position: [74, 42]
      - position: [63, 20]
      - position: [50, 5]
      - position: [30, 0]
      - position: [3, 2]
        alias: plinth-near
      resolution: 2
    lip:
      inset: -0.6
      height: 1.5
    pad:
      height:
        surface-range: 8
        lip-to-surface: 3
        below-lip: 2
      surface:
        edge:
          inset: 8
          resolution: 5
  rotation:
    pitch: 0.05
    roll: 0.05
  sprues:
    include: true
    inset: 10
    diameter: 12
    positions:
    - anchor: plinth-middle
      offset: [0, -10]
    - anchor: plinth-right
      offset: [-5, -10]
  bottom-plate:
    include: true
    inset: 2
    fastener-positions:
    - anchor: plinth-middle
      offset: [0, -3]
    - anchor: plinth-near
      offset: [3, 3]
    - anchor: plinth-right
      offset: [-2, -3]
